version: '2'
services:
  iop-can:
    image: libertaria/iop-can
    ports:
      - 14001:14001
      - 14002:14002
      - 127.0.0.1:15001:15001
      - 18080:18080
    volumes:
      - /opt/ipfs:/data/ipfs